name: CI

on:
  push:
    branches: [main, developer]

  pull_request:
    branches: [main, developer]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"

      - name: Install dependencies (root)
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
